/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wattlegalcoursework;

import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Reuben
 */
public class TimeAndDate extends javax.swing.JPanel {

    /**
     * Creates new form TimeAndDate
     */
    public TimeAndDate() {
        initComponents();
        Clock();
    }
    
    public void Clock() {
        Thread ClockThread = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar time = Calendar.getInstance();

                        SimpleDateFormat hourminutesecond = new SimpleDateFormat("HH:mm:ss");
                        SimpleDateFormat daymonthyear = new SimpleDateFormat("dd:MM:yyyy");
                        String localtime = (hourminutesecond.format(time.getTime()));
                        String date = daymonthyear.format(new Date());
                        lblClock.setText(localtime);
                        lblDate.setText(date);
                        sleep(1000);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(TimeAndDate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        ClockThread.start();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 0));

        lblDate.setText("Date");

        lblClock.setText("Clock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClock)
                    .addComponent(lblDate))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    // End of variables declaration//GEN-END:variables
}
